config/routes.rb
Cinema::Application.routes.draw do
  get "about/index"
  get "home/index"
  root :to =>"home#index"
  resources :moviees

  resources :genres

  

end

app/models/genre.rb
class Genre < ActiveRecord::Base
	has_many :moviees

	def self.search(search)
  		if search
    		find(:all, :conditions => ['name LIKE ?', "%#{search}%"])
  		else
    		find(:all)
  		end
	end
end

app/models/moviee.rb
class Moviee < ActiveRecord::Base
	validates :genre_id, :name, :author, :country, :publish, presence: true

	
	belongs_to :genre

	def self.search(search)
  		if search
    		find(:all, :conditions => ['name LIKE ?', "%#{search}%"])
  		else
    		find(:all)
  		end
	end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :set_genre, only: [:show, :edit, :update, :destroy]

  # GET /genres
  # GET /genres.json
  def index
    @genres = Genre.search(params[:search])
  end

  # GET /genres/1
  # GET /genres/1.json
  def show
  end

  # GET /genres/new
  def new
    @genre = Genre.new
  end

  # GET /genres/1/edit
  def edit
  end

  # POST /genres
  # POST /genres.json
  def create
    @genre = Genre.new(genre_params)

    respond_to do |format|
      if @genre.save
        format.html { redirect_to @genre, notice: 'Genre was successfully created.' }
        format.json { render action: 'show', status: :created, location: @genre }
      else
        format.html { render action: 'new' }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /genres/1
  # PATCH/PUT /genres/1.json
  def update
    respond_to do |format|
      if @genre.update(genre_params)
        format.html { redirect_to @genre, notice: 'Genre was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /genres/1
  # DELETE /genres/1.json
  def destroy
    @genre.destroy
    respond_to do |format|
      format.html { redirect_to genres_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_genre
      @genre = Genre.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def genre_params
      params.require(:genre).permit(:id_genre, :name, :description)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/moviees_controller.rb
class MovieesController < ApplicationController
  before_action :set_moviee, only: [:show, :edit, :update, :destroy]

  # GET /moviees
  # GET /moviees.json
  def index
    @moviees = Moviee.search(params[:search])
  end

  # GET /moviees/1
  # GET /moviees/1.json
  def show
  end

  # GET /moviees/new
  def new
    @moviee = Moviee.new
  end

  # GET /moviees/1/edit
  def edit
  end

  # POST /moviees
  # POST /moviees.json
  def create
    @moviee = Moviee.new(moviee_params)

    respond_to do |format|
      if @moviee.save
        format.html { redirect_to @moviee, notice: 'Moviee was successfully created.' }
        format.json { render action: 'show', status: :created, location: @moviee }
      else
        format.html { render action: 'new' }
        format.json { render json: @moviee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /moviees/1
  # PATCH/PUT /moviees/1.json
  def update
    respond_to do |format|
      if @moviee.update(moviee_params)
        format.html { redirect_to @moviee, notice: 'Moviee was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @moviee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /moviees/1
  # DELETE /moviees/1.json
  def destroy
    @moviee.destroy
    respond_to do |format|
      format.html { redirect_to moviees_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_moviee
      @moviee = Moviee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def moviee_params
      params.require(:moviee).permit(:genre_id, :name, :author, :country, :publish)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/moviees_helper.rb
module MovieesHelper
end

app/views/about/index.html.erb
<h1><font color="#fff">About Me</font></h1>

<li>
    <%= image_tag('IMG_5833.jpg')  %>
  </li>

<br>
  <p><font color="#faa">ญาดา มณีจักรชนะกุล</font></p>
<p><font color="#fcf">5310450483</font></p>


 

app/views/genres/_form.html.erb
<%= form_for(@genre) do |f| %>
  <% if @genre.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@genre.errors.count, "error") %> prohibited this genre from being saved:</h2>

      <ul>
      <% @genre.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id_genre %><br>
    <%= f.number_field :id_genre %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/genres/edit.html.erb
<h1>Editing genre</h1>

<%= render 'form' %>

<%= link_to 'Show', @genre %> |
<%= link_to 'Back', genres_path %>

app/views/genres/index.html.erb
<h1><font color="#F2F5A9">Listing genres</font></h1>


<%= form_tag genres_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>
<table>
  <thead>
    <tr>
      <th><font color="#0080FF"> Id genre </font></th>
      <th><font color="#0080FF"> Name</font></th>
      <th><font color="#0080FF"> Description</font></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @genres.each do |genre| %>
      <tr>
        <td><%= genre.id_genre %></td>
        <td><%= genre.name %></td>
        <td><%= genre.description %></td>
        <td><%= link_to 'Show', genre %></td>
        <td><%= link_to 'Edit', edit_genre_path(genre) %></td>
        <td><%= link_to 'Destroy', genre, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Genre', new_genre_path, class: "button success" %>

app/views/genres/new.html.erb
<h1>New genre</h1>

<%= render 'form' %>

<%= link_to 'Back', genres_path %>

app/views/genres/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id genre:</strong>
  <%= @genre.id_genre %>
</p>

<p>
  <strong>Name:</strong>
  <%= @genre.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @genre.description %>
</p>

<%= link_to 'Edit', edit_genre_path(@genre) %> |
<%= link_to 'Back', genres_path %>

app/views/home/index.html.erb
<br><br>
<h2><marquee direction=right>MOVIE</marquee><h2>

<ul data-orbit>
  <li>
    <%= image_tag('avatar.jpg')  %>
    <div class="orbit-caption" >...</div>
  </li>
  <li>
    <%= image_tag('harry.jpg') %>
    <div class="orbit-caption" >...</div>
  </li>
  <li>
    <%= image_tag('Iron2.jpg') %>
    <div class="orbit-caption">...</div>
  </li>
  <li>
    <%= image_tag('resdenti.jpg') %>
    <div class="orbit-caption">...</div>
  </li>
</ul>

  <!-- Prev/Next Arrows -->
  <a href="#" class="orbit-prev"> <span></span></a>
  <a href="#" class="orbit-next"> <span></span></a>

  <!-- Slide Numbers -->
  <div class="orbit-slide-number">
    <span></span><span></span>
  </div>

  <!-- Timer and Play/Pause Button -->
  <div class="orbit-timer">
    <span></span>
    <div class="orbit-progress" style="width: 100%; -webkit-transition: width 5s linear;"></div>
  </div>
</div>

<!-- Orbit Bullet Slide Indicator -->
<ol class="orbit-bullets">
  <li data-orbit-slide-number="1"></li>
  <li data-orbit-slide-number="2" class="active"></li>
  <li data-orbit-slide-number="3"></li>
</ol>

</div>
</div>


    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "application" ,data: { "no_turbolink" => true } %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <nav class="top-bar">
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to "Movie Home", ".." ,data: { "no_turbolink" => true}%></a></h1>
    </li>
  </ul>


  <section class="top-bar-section">
  
    <ul class="right">

      <li class="divider"></li>
      <li><%= link_to "Browse Movie", moviees_path %></li>
      <li class="divider"></li>
      <li><%= link_to "Category", genres_path %></li>
      <li class="divider"></li>
      <li><a href="about/index">About</a></li>
      
    </ul>

  </div>
</nav>

<div class="row">
  <div class="small-10 columns"><%= yield %></div>
  
</div>
  </body>
</html>

app/views/moviees/_form.html.erb
<%= form_for(@moviee) do |f| %>
  <% if @moviee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@moviee.errors.count, "error") %> prohibited this moviee from being saved:</h2>

      <ul>
      <% @moviee.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :genre_id , title: "แนวหนัง", data: {tooltip: true} %><br>
    <%= f.collection_select :genre_id, Genre.all,

          :id, :name, { prompt: true, length: 25 },

          { style: "width: 150px;" } %>
  </div>
  <div class="field">
    <%= f.label :name , title: "ชื่อหนัง", data: {tooltip: true} %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :author , title: "ผู้แต่ง", data: {tooltip: true} %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :country , title: "ประเทศ", data: {tooltip: true} %><br>
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :publish , title: "ออกอากาศ", data: {tooltip: true} %><br>
    <%= f.text_field :publish %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/moviees/edit.html.erb
<h1>Editing moviee</h1>

<%= render 'form' %>

<%= link_to 'Show', @moviee %> |
<%= link_to 'Back', moviees_path %>

app/views/moviees/index.html.erb
<h1><font color="white">Listing Moviees</font></h1>

<%= form_tag moviees_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>

<table>
  <thead>
    <tr>
      <th style="color:#000;">Genre</th>
      <th>Name</th>
      <th>Author</th>
      <th>Country</th>
      <th>Publish</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>


  <tbody>
    <% @moviees.each do |moviee| %>
      <tr>
        <td><%= moviee.genre.name %></td>
        <td><%= moviee.name %></td>
        <td><%= moviee.author %></td>
        <td><%= moviee.country %></td>
        <td><%= moviee.publish %></td>
        <td><%= link_to 'Show', moviee %></td>
        <td><%= link_to 'Edit', edit_moviee_path(moviee) %></td>
        <td><%= link_to 'Destroy', moviee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% end %>
  </tbody>
</table>


<%= link_to 'New Moviee', new_moviee_path %>

app/views/moviees/new.html.erb
<h1>New moviee</h1>

<%= render 'form' %>

<%= link_to 'Back', moviees_path %>

app/views/moviees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Genre:</strong>
  <%= @moviee.genre_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @moviee.name %>
</p>

<p>
  <strong>Author:</strong>
  <%= @moviee.author %>
</p>

<p>
  <strong>Country:</strong>
  <%= @moviee.country %>
</p>

<p>
  <strong>Publish:</strong>
  <%= @moviee.publish %>
</p>

<%= link_to 'Edit', edit_moviee_path(@moviee) %> |
<%= link_to 'Back', moviees_path %>